// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function envExt(env, name, sem, name2) {
  if (name === name2) {
    return sem;
  } else {
    return Curry._1(env, name2);
  }
}

function evaluate(m, e) {
  switch (m.tag | 0) {
    case 0 : 
        return Curry._1(e, m[0]);
    case 1 : 
        var n = m[2];
        var name = m[0];
        return /* MAbs */Block.__(1, [(function (sem) {
                      return evaluate(n, (function (param) {
                                    return envExt(e, name, sem, param);
                                  }));
                    })]);
    case 2 : 
        var sem1opt = evaluate(m[0], e);
        var sem2opt = evaluate(m[1], e);
        if (sem1opt !== undefined && sem2opt !== undefined) {
          var sem1 = sem1opt;
          if (sem1.tag) {
            return Curry._1(sem1[0], sem2opt);
          } else {
            return undefined;
          }
        } else {
          return undefined;
        }
    
  }
}

exports.envExt = envExt;
exports.evaluate = evaluate;
/* No side effect */
