// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

function envExt(env, name, sem, name2) {
  if (name === name2) {
    return sem;
  } else {
    return Curry._1(env, name2);
  }
}

var Wrong_application = Caml_exceptions.create("Demo-NbeReason.Wrong_application");

function evaluate(m, e) {
  switch (m.tag | 0) {
    case 0 : 
        return Curry._1(e, m[0]);
    case 1 : 
        var n = m[2];
        var name = m[0];
        return /* MAbs */Block.__(1, [(function (sem) {
                      return evaluate(n, (function (param) {
                                    return envExt(e, name, sem, param);
                                  }));
                    })]);
    case 2 : 
        var sem1 = evaluate(m[0], e);
        var sem2 = evaluate(m[1], e);
        if (sem1.tag) {
          return Curry._1(sem1[0], sem2);
        } else {
          throw Wrong_application;
        }
    
  }
}

exports.envExt = envExt;
exports.Wrong_application = Wrong_application;
exports.evaluate = evaluate;
/* No side effect */
